import { type NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import { useDebounce } from "~/utils/helpers";
import { api } from "~/utils/api";
import { Smoothies } from "~/components/smoothies/Smoothies";

const Home: NextPage = () => {
  const [filter, setFilter] = useState("");
  const debouncedFilterValue = useDebounce(filter, 300);
  const { data: smoothiesFiltered, refetch: refetchSmoothiesFiltered } =
    api.smoothies.getAllFiltered.useQuery({
      smoothieTitle: debouncedFilterValue,
    });

  return (
    <>
      <Head>
        <title>Create Smoothie App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="w-full pt-32 text-center">
        <input
          onChange={(e) => {
            setFilter(e.target.value);
          }}
          placeholder="Search Smoothie"
          className="input font-bold"
        />
      </div>
      {smoothiesFiltered && (
        <Smoothies
          smoothiesFiltered={smoothiesFiltered}
          onRefetch={refetchSmoothiesFiltered}
        />
      )}
    </>
  );
};

export default Home;
