import { type NextPage } from "next";
import Head from "next/head";

import { api } from "~/utils/api";

const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "from tRPC ❤️" });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <p className="flex min-h-screen flex-col items-center justify-center  text-white">
        <h1 className="text-5xl">{hello?.data && hello.data.greeting}</h1>
      </p>
    </>
  );
};

export default Home;
